FROM node:18.18

#Create a app directory
WORKDIR /v2

#Install app dependencies
COPY package*.json ./

#Run npm install
RUN npm install

#Bundle app souce
COPY . .

EXPOSE 8080

CMD [ "npm", "run","dev" ]